---

# Docker Installation Playbook for CentOS 7
# https://docs.docker.com/install/linux/docker-ce/centos/
# https://docs.ansible.com/ansible/latest/modules/yum_module.html
# https://docs.ansible.com/ansible/latest/modules/yum_repository_module.html
# https://docs.ansible.com/ansible/latest/plugins/lookup/items.html
# https://docs.ansible.com/ansible/latest/modules/service_module.html

- hosts: docker
  become: yes
  become_user: root
  become_method: sudo


  tasks:

    - name: install docker on CentOS 7
      block:

      - name: uninstall old versions
        yum:
          name: "{{ item }}"
          state: absent
        with_items:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-selinux
          - docker-engine-selinux
          - docker-engine

      - name: install required packages
        yum:
          name: "{{ item }}"
          state: present
        with_items:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2

      - name: add yum repository for docker-ce
        yum_repository:
          name: docker-ce-stable
          file: docker-ce
          description: Docker CE Stable - $basearch
          baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
          enabled: no
          gpgcheck: yes
          gpgkey: https://download.docker.com/linux/centos/gpg

      - name: install docker-ce
        yum:
          name: docker-ce
          state: present
          enablerepo: docker-ce-stable
        notify:
          - restart docker-ce

      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7


  handlers:

    - name: restart docker-ce
      service:
        name: docker
        state: restarted
        enabled: yes

