---

- hosts: ap
  become: yes
  become_user: root
  become_method: sudo

  tasks:

     - name: restart zabbix agent at version 7
       when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7
       command: "{{ item }}"
       with_items:
           #- firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv4" source address="221.148.82.216/32" service name="ssh" accept'
        - firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv4" source address="221.148.82.216/32" accept'
        - firewall-cmd --reload

     - name: restart zabbix agnet at version 6 
       when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6
       command: "{{ item }}"
       with_items:
           #- iptables -I RH-Firewall-1-INPUT 20 -s 221.148.82.216/32 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
        - iptables -I RH-Firewall-1-INPUT 20 -s 221.148.82.216/32 -p tcp -m state --state NEW -m tcp -j ACCEPT
        - service iptables save
        - service iptables restart
