---

- hosts: maria, maria10.2, maria10.3, mysql
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - '{{ inventory_dir }}/vars/{{ project }}_maria.yml'

  tasks:

    - name: is mariadb installed from RPM
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      shell: ls /var/lib/mysql
      ignore_errors: yes
      register: rpm_mariadb

    - name: install required packages
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      yum: name=perl-Cache-Cache,perl-DBD-MySQL state=present enablerepo=epel

    - name: create mariadb munin plugin
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      copy: src={{ inventory_dir }}/files/maria/munin/plugins/mariadb_ dest=/usr/share/munin/plugins/mariadb_ owner=root group=root mode=0755

    - name: configuration mariadb munin plugin
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      template: src={{ inventory_dir }}/templates/maria/munin/plugin-conf.d/mysql.j2 dest=/etc/munin/plugin-conf.d/mysql

    - name: create symlink munin plugins
      notify: restart munin-node
      file: src=/usr/share/munin/plugins/mariadb_ dest=/etc/munin/plugins/mysql_{{ item }} owner=root group=root state=link
      with_items:
        - 'bin_relay_log'
        - 'commands'
        - 'connections'
        - 'files_tables'
        - 'handlers'
        - 'innodb_bpool'
        - 'innodb_bpool_act'
        - 'innodb_checkpoint_age'
        - 'innodb_insert_buf'
        - 'innodb_io'
        - 'innodb_io_pend'
        - 'innodb_log'
        - 'innodb_rows'
        - 'innodb_semaphores'
        - 'innodb_tnx'
        - 'myisam_indexes'
        - 'network_traffic'
        - 'processlist'
        - 'qcache'
        - 'qcache_mem'
        - 'replication'
        - 'select_types'
        - 'slow'
        - 'sorts'
        - 'table_locks'
        - 'threads'
        - 'tmp_tables'

  handlers:

    - name: restart munin-node
      service: name=munin-node state=restarted enabled=yes
