---

- hosts: maria, maria10.2, maria10.3, mysql
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - '{{ inventory_dir }}/vars/{{ project }}_maria.yml'

  tasks:

    - name: configure access to mysql from zabbix-agent
      template: src={{ inventory_dir }}/templates/maria/zabbix/my.cnf.j2 dest=/etc/zabbix/my.cnf

    - name: configure zabbix-agent user parameter
      notify: restart zabbix-agent
      template: src={{ inventory_dir }}/templates/maria/zabbix/zabbix_agentd.d/userparameter_mysql.conf.j2 dest=/etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf

  handlers:

    - name: restart zabbix-agent
      service: name=zabbix-agent state=restarted enabled=yes
