---

- hosts: redis
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - '{{ inventory_dir }}/vars/{{ project }}_redis.yml'

  tasks:

    - name: install required packages
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      yum: name=perl-Redis state=present enablerepo=epel

    - name: install perl-Switch packages(centos7)
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")
      yum: name=perl-Switch state=present

    - name: install perl-Switch packages(centos8) 
      when: location != 'gcp' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 8
      dnf: name=perl-Switch enablerepo=PowerTools state=present

    - name: install perl-Switch packages(centos8)
      when: location == 'gcp' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 8
      dnf: name=perl-Switch enablerepo=powertools state=present

    - name: create redis munin plugin
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      copy: src={{ inventory_dir }}/files/redis/munin/plugins/redis_ dest=/usr/share/munin/plugins/redis_ owner=root group=root mode=0755

    - name: configuration redis munin plugin
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      template: src={{ inventory_dir }}/templates/redis/munin/plugin-conf.d/redis.j2 dest=/etc/munin/plugin-conf.d/redis


    - name: create symlink munin plugins
      notify: restart munin-node
      file: src=/usr/share/munin/plugins/redis_ dest=/etc/munin/plugins/redis_{{ item }} owner=root group=root state=link
      with_items:
        - 'connected_clients'
        - 'key_raito'
        - 'key_per_sec'
        - 'per_sec'
        - 'used_keys'
        - 'used_memory'

    - name: create redis-speed plugin
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      copy: src={{ inventory_dir }}/files/redis/munin/plugins/redis-speed dest=/usr/share/munin/plugins/redis-speed owner=root group=root mode=0755

    - name: create symlink redis-speed plugin
      notify: restart munin-node
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      file: src=/usr/share/munin/plugins/redis-speed dest=/etc/munin/plugins/redis-speed owner=root group=root state=link


  handlers:

    - name: restart munin-node
      service: name=munin-node state=restarted enabled=yes
