---

- hosts: redis
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: set kernel parameter for redis
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      lineinfile: dest=/etc/rc.d/rc.local line={{ item }}
      with_items:
        - 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
