---

- hosts: redis
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - '{{ inventory_dir }}/vars/{{ project }}_redis.yml'

  tasks:

    - name: configure zabbix-agent user parameter
      notify: restart zabbix-agent
      template: src={{ inventory_dir }}/templates/redis/zabbix/zabbix_agentd.d/userparameter_redis.conf.j2 dest=/etc/zabbix/zabbix_agentd.d/userparameter_redis.conf

  handlers:

    - name: restart zabbix-agent
      service: name=zabbix-agent state=restarted enabled=yes
