---

- hosts: wp
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: Install remi repository
      when: ansible_distribution == 'CentOS'
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
        state: present

    - name: find remi repo files
      when: ansible_distribution == 'CentOS'
      find: paths='/etc/yum.repos.d' patterns='remi-*.repo'
      register: remi_repo_list


    - name: disable remi repo by default
      when: ansible_distribution == 'CentOS'
      replace: dest={{ item.path }} regexp="^enabled *=.*" replace="enabled=0"
      with_items:
        - '{{ remi_repo_list.files }}'

    - name: install php 7.1
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7
      yum:
        name: php,php-cli,php-common,php-devel,php-fpm,php-gd,php-mbstring,php-mysqlnd,php-pdo,php-pear,php-pecl-apcu,php-xdebug,php-opcache
        state: present
        enablerepo: epel,remi-safe,remi-php71

    - name: configure nginx
      when: ansible_distribution == 'CentOS'
      notify: restart nginx
      copy: src={{ inventory_dir }}/files/wp/nginx/nginx.conf dest=/etc/nginx/nginx.conf

    - name: configure nginx
      when: ansible_distribution == 'CentOS'
      notify: restart nginx
      copy: src={{ inventory_dir }}/files/wp/nginx/example.com.conf dest=/etc/nginx/conf.d/example.com.conf

    - name: configure php
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7
      notify: restart php-fpm
      copy: src={{ inventory_dir }}/files/wp/php.ini dest=/etc/php.ini

    - name: configure php
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7
      notify: restart php-fpm
      copy: src={{ inventory_dir }}/files/wp/php.d/10-opcache.ini dest=/etc/php.d/10-opcache.ini

    - name: configure php
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7
      notify: restart php-fpm
      copy: src={{ inventory_dir }}/files/wp/php-fpm.d/www.conf dest=/etc/php-fpm.d/www.conf

  handlers:

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes

    - name: restart php-fpm
      service: name=php-fpm state=restarted enabled=yes
