---

- hosts: mq
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: configure ulimit
      pam_limits: dest=/etc/security/limits.conf domain={{ item.domain }} limit_type={{ item.type }} limit_item={{ item.item }} value={{ item.value }}
      with_items:
        - { domain: 'root', type: 'soft', item: 'nofile', value: '131072' }
        - { domain: 'root', type: 'hard', item: 'nofile', value: '131072' }
        - { domain: 'rabbitmq', type: 'soft', item: 'nofile', value: '131072' }
        - { domain: 'rabbitmq', type: 'hard', item: 'nofile', value: '131072' }
        - { domain: 'www', type: 'soft', item: 'nofile', value: '131072' }
        - { domain: 'www', type: 'hard', item: 'nofile', value: '131072' }
