---

- hosts: ansible
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: create private key for ansible user
      copy: src="{{ inventory_dir }}/private/ansible_{{ env }}_id_rsa" dest=/home/ansible/.ssh/id_rsa mode=0600 owner=ansible group=ansible

    - name: ansible user ssh_config
      copy: src={{ inventory_dir }}/files/ansible/ansible_ssh_config dest=/home/ansible/.ssh/config
