- name: Elasticsearch with custom configuration
  hosts: es_single_node
  roles:
    - role: roles/elasticsearch
  vars:
   #es_version: 7.10.2  # Enter the appropriate version for your environment
    es_data_dirs:
      - "/usr/local/elasticsearch/data"
    es_log_dir: "/usr/local/elasticsearch/logs"
    es_config:
      node.name: "node1"
      http.port: 9200
      node.data: true    # when using data is true. false is arbiter.
      node.master: true
      bootstrap.memory_lock: false    # if don't use swap space
      network.host: 0.0.0.0
      discovery.type: single-node
   #es_heap_size: 4g    # if instance memory is setting 8GB and you have to setting 4g.  ex 32/8=4
    es_start_service: yes
    es_api_port: 9200   # default is 9200.
    es_plugins:
      - plugin: ingest-attachment
