---

- import_playbook: './playbooks/common/messages.yml'
- import_playbook: './playbooks/common/swap.yml'
- import_playbook: './playbooks/common/NetworkManager.yml'
- import_playbook: './playbooks/common/epel.yml'
- import_playbook: './playbooks/common/ius.yml'
- import_playbook: './playbooks/common/package.yml'
- import_playbook: './playbooks/common/selinux.yml'
- import_playbook: './playbooks/common/hostname.yml'
- import_playbook: './playbooks/common/timezone.yml'
- import_playbook: './playbooks/common/firewall.yml'
- import_playbook: './playbooks/common/user_root.yml'
- import_playbook: './playbooks/common/user_infra.yml'
- import_playbook: './playbooks/common/user_coco.yml'
- import_playbook: './playbooks/common/user_www.yml'
- import_playbook: './playbooks/common/user_dev_kr.yml'
- import_playbook: './playbooks/common/user_anysense.yml'
- import_playbook: './playbooks/common/user_ansible.yml'
- import_playbook: './playbooks/common/sudo.yml'
- import_playbook: './playbooks/common/ntp.yml'
- import_playbook: './playbooks/common/sysctl_net.yml'
- import_playbook: './playbooks/common/sysctl_vm.yml'
- import_playbook: './playbooks/common/ulimit.yml'
- import_playbook: './playbooks/common/sshd.yml'
- import_playbook: './playbooks/common/sshd-monitor.yml'
- import_playbook: './playbooks/common/postfix.yml'
- import_playbook: './playbooks/common/awscli.yml'
- import_playbook: './playbooks/common/munin-node.yml'
- import_playbook: './playbooks/common/zabbix-agent.yml'
- import_playbook: './playbooks/common/rclocal.yml'
- import_playbook: './playbooks/common/tuned.yml'
- import_playbook: './playbooks/common/profile.yml'
- import_playbook: './playbooks/common/yum-cron.yml'
- import_playbook: './playbooks/common/yum_update.yml'
- import_playbook: './playbooks/common/crond.yml'
- import_playbook: './playbooks/ap/firewall.yml'
- import_playbook: './playbooks/ap/sysctl.yml'
- import_playbook: './playbooks/ap/user_coco.yml'
- import_playbook: './playbooks/ap/user_www.yml'
- import_playbook: './playbooks/ap/munin-plugins.yml'
- import_playbook: './playbooks/ap/munin-plugins_nginx.yml'
- import_playbook: './playbooks/ap/loopback.yml'
- import_playbook: './playbooks/ap/loopback_apbill.yml'
- import_playbook: './playbooks/ap/nginx.yml'
- import_playbook: './playbooks/cms/user_cms.yml'
- import_playbook: './playbooks/maria/sysctl.yml'
- import_playbook: './playbooks/maria/ulimit.yml'
- import_playbook: './playbooks/mysql/mysql.yml'
- import_playbook: './playbooks/maria/mariadb.yml'
- import_playbook: './playbooks/maria/mariadb-10.2.yml'
- import_playbook: './playbooks/maria/mariadb-10.3.yml'
- import_playbook: './playbooks/maria/mariadb-10.4.yml'
- import_playbook: './playbooks/maria/munin-plugins.yml'
- import_playbook: './playbooks/maria/zabbix-agent.yml'
- import_playbook: './playbooks/mongo/firewall.yml'
- import_playbook: './playbooks/mongo/sysctl.yml'
- import_playbook: './playbooks/mongo/ulimit.yml'
- import_playbook: './playbooks/mongo/rclocal.yml'
- import_playbook: './playbooks/mongo/atime.yml'
- import_playbook: './playbooks/mongo/zabbix-agent_mongod.yml'
- import_playbook: './playbooks/mongo/zabbix-agent_mongos.yml'
- import_playbook: './playbooks/mongo/zabbix-agent_mongoc.yml'
- import_playbook: './playbooks/redis/sysctl.yml'
- import_playbook: './playbooks/redis/munin-plugins.yml'
- import_playbook: './playbooks/redis/zabbix-agent.yml'
- import_playbook: './playbooks/redis/rclocal.yml'
- import_playbook: './playbooks/mq/munin-plugins.yml'
- import_playbook: './playbooks/mq/sysctl.yml'
- import_playbook: './playbooks/mq/ulimit.yml'
- import_playbook: './playbooks/elasticsearch/es_singlenode.yml'
- import_playbook: './playbooks/elasticsearch/es_masternode.yml'
- import_playbook: './playbooks/elasticsearch/es_datanode_1.yml'
- import_playbook: './playbooks/elasticsearch/es_arbiter.yml'
- import_playbook: './playbooks/ansible/user_ansible.yml'
