---

- hosts: zabbix-server
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: Add Yum zabbix_repository
      yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
        state: present

    - name: Add Yum iksemel
      yum:
        name: http://springdale.math.ias.edu/data/puias/unsupported/7/x86_64//iksemel-1.4-6.sdl7.x86_64.rpm
        state: present

    - name: Add Yum zabbix_server
      yum:
        name: '{{ item }}'
        state: latest
        enablerepo: epel,zabbix
        disable_gpg_check: yes
      with_items:
        - fping
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-web-japanese
        - mysql

    - name: Add Yum mariadb-server
      yum:
        name: '{{ item }}'
        state: latest
        enablerepo: epel,zabbix
        disable_gpg_check: yes
      with_items:
        - mariadb-server
      when: location == 'nbp'

    - name: Modify zabbix-server setting files
      notify: Restart Systemd zabbix_server
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.owner }}"
        mode: "{{ item.mode }}"
      with_items:
        - { src: "{{ inventory_dir }}/templates/zabbix-server/etc/zabbix/zabbix_server.conf", dest: "/etc/zabbix/zabbix_server.conf",  owner: root,  mode: 644 }
        - { src: "{{ inventory_dir }}/templates/zabbix-server/etc/zabbix/web/zabbix.conf.php", dest: "/etc/zabbix/web/zabbix.conf.php",  owner: apache,  mode: 644 }
      tags: zabbix_server-setting

    #- name: Modify the httpd documentroot
    #  lineinfile:
    #    dest: '/etc/httpd/conf.d/zabbix.conf'
    #    regexp: 'Alias /zabbix /usr/share/zabbix'
    #    line: 'DocumentRoot /usr/share/zabbix'
    #    backrefs: yes

    - name: Modify the php timezone
      lineinfile:
        dest: '/etc/php.ini'
        regexp: ';date.timezone ='
        line: 'date.timezone = Asia/Tokyo'
        backrefs: yes
    
    - name: Restart httpd service
      systemd:
        name: httpd
        state: restarted
        enabled: yes

  handlers:

    - name: Restart Systemd zabbix_server
      systemd:
        name: zabbix-server
        state: restarted
        enabled: yes
