---

- hosts: mysql
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - '{{ inventory_dir }}/vars/{{ project }}_maria.yml'

  tasks:

    - name: Alias setting for MariaDB operation
      when: ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")) and ansible_architecture == "x86_64"
      copy: src={{ inventory_dir }}/files/maria/bash_profile dest=/root/.bash_profile owner=root group=root mode=0644

    - name: install required package
      when: ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")) and ansible_architecture == "x86_64"
      yum: name=MySQL-python state=present

    - name: install mysql-community-release
      when: ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")) and ansible_architecture == "x86_64"
      yum:
        name: http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
        state: present

    - name: disable mysql-community repo by default
      when: ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")) and ansible_architecture == "x86_64"
      replace: dest={{ item }} regexp="^enabled *=.*" replace="enabled=0"
      with_items:
        - "/etc/yum.repos.d/mysql-community.repo"
        - "/etc/yum.repos.d/mysql-community-source.repo"

    - name: install MySQL
      when: ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")) and ansible_architecture == "x86_64"
      yum: name="mysql-community-server" enablerepo=mysql57-community state=present
      notify:
        - stop MySQL

  handlers:

    - name: stop MySQL
      when: ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")) and ansible_architecture == "x86_64"
      service: name=mysqld state=stopped enabled=no
