---

- hosts: mongo, mongod
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - '{{ inventory_dir }}/vars/{{ project }}_mongo.yml'

  tasks:

    - name: configure zabbix-agent mongod user parameter
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      notify: restart zabbix-agent
      template: src={{ inventory_dir }}/templates/mongo/zabbix_agentd.d/userparameter_mongod.conf.j2 dest=/etc/zabbix/zabbix_agentd.d/userparameter_mongodb.conf

    - name: configure zabbix-agent mongod user parameter
      when: ansible_distribution == 'Ubuntu'
      notify: restart zabbix-agent
      template: src={{ inventory_dir }}/templates/mongo/zabbix_agentd.d/userparameter_mongod.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf.d/userparameter_mongodb.conf

  handlers:

    - name: restart zabbix-agent
      service: name=zabbix-agent state=restarted enabled=yes
