---

- hosts: ap, apbill, wp, maint
  become: yes
  become_user: root
  become_method: sudo
  vars:
    aws_api_access_key: "{{ lookup('file', '{{ inventory_dir }}/private/aws-elb-reg_aws_api_access_key') }}"
    aws_api_secret_key: "{{ lookup('file', '{{ inventory_dir }}/private/aws-elb-reg_aws_api_secret_key') }}"

  tasks:

    - name: Install ELB registration script CentOS 6 only.
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 6 and location is match('aws')
      yum: name=aws-elb-reg enablerepo=cocone state=present

    - name: ELB registration script file
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location is match('aws')
      notify: start ELB registration
      copy: src='{{ inventory_dir }}/files/ap/aws-elb-reg.sbin' dest=/usr/sbin/aws-elb-reg mode=0755

    - name: ELB registration systemd unit file
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location is match('aws')
      notify:
        - systemd daemon reload
        - start ELB registration
      copy: src='{{ inventory_dir }}/files/ap/aws-elb-reg.systemd' dest=/etc/systemd/system/aws-elb-reg.service

    - name: ELB registration environment file
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 6 and location is match('aws')
      notify: start ELB registration
      template: src='{{ inventory_dir }}/templates/ap/aws-elb-reg.env.j2' dest=/etc/sysconfig/aws-elb-reg

  handlers:

    - name: systemd daemon reload
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location is match('aws') and env == 'real'
      command: /bin/systemctl daemon-reload

    - name: start ELB registration
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 6 and location is match('aws') and env == 'real'
      service: name=aws-elb-reg state=started enabled=yes
      ignore_errors: yes
