---

- hosts: ap
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: add infra user pubkey
      when: project == 'corporate'
      authorized_key: user=infra key="{{ item }}"
      with_file:
        - "{{ inventory_dir }}/private/public_keys/infra"
