#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

GETNUM=`/bin/sh /home/coco/bin/app/munin_rth.sh`

if [ "$1" = "autoconf" ]; then
        if [ -n ${GETNUM} ] ; then
                echo yes
                exit 0
        else
                echo no
                exit 0
        fi
fi

if [ "$1" = "config" ]; then
        echo 'graph_title Tomcat Thread(RTH)'
        echo 'graph_args -r --lower-limit 0'
        echo 'graph_vlabel threads'
        echo 'graph_category Apps'
        echo 'total.label Total threads'
        echo 'total.min 0'
        echo 'total.draw LINE2'
        echo 'total.type GAUGE'
        exit 0
fi

echo "total.value $GETNUM";

