#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

CATEGORY="dbcp2"
TITLE="Pool (CA_BILL)"
DATASOURCE="BoneCP CA_BILL : "
TOMCAT_PORT="4930"
RESULT=$(curl -s http://127.0.0.1:${TOMCAT_PORT}/ca/rpc/startup/etc/dbcpstatus | sed -e 's/{"response":{"success":true,"dbcpstatus":"//g' |  sed -e 's/\\n/\n/g' | grep "CA")

LEASED=$(echo "${RESULT}" | grep "${DATASOURCE}" | awk -F "," '{print $1}' | awk -F "=" '{print $2}')
FREE=$(echo "${RESULT}" | grep "${DATASOURCE}"  | awk -F "," '{print $2}' | awk -F "=" '{print $2}')
TOTAL=$(echo "${RESULT}" | grep "${DATASOURCE}" | awk -F "," '{print $3}' | awk -F "=" '{print $2}')


if [ "$1" = "autoconf" ]; then
        if [ -n ${TOTAL} ] ; then
                echo yes
                exit 0
        else
                echo no
                exit 0
        fi
fi


if [ "$1" = "config" ]; then
    echo "graph_title $TITLE";
    echo "graph_args --base 1000 -l 0";
    echo "graph_vlabel connections";
    echo "graph_category $CATEGORY";
    echo "graph_total total";
    echo "graph_order leased free";
    echo "leased.label leased connections";
    echo "leased.draw AREA";
    echo "free.label free connections";
    echo "free.draw STACK";
    exit 0;
fi


if [ ${TOTAL} -gt 0 ]; then
    echo "leased.value $LEASED";
    echo "free.value $FREE";
else
    echo "leased.value U";
    echo "free.value U";
fi
