---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - block:
      - name: download awscliv2
        unarchive:
          src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
          dest: /root
          remote_src: yes
        ignore_errors: yes

      - name: install awscliv2
        command: /root/aws/install --update

      when: location is match('aws') and ansible_distribution == 'CentOS'
