---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: install epel-release
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
      yum: name=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

    - name: install epel-release
      when: location != 'ten' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7
      yum: name=epel-release state=present

    - name: install epel-release for AmazonLinux2
      when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

    - name: disable epel repo by default
      when: location != 'ten' and (ansible_distribution == 'CentOS' or ansible_distribution == "Amazon")
      replace: dest={{ item }} regexp="^enabled *=.*" replace="enabled=0"
      with_items:
        - "/etc/yum.repos.d/epel.repo"
        - "/etc/yum.repos.d/epel-testing.repo"
