---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: install firewalld
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location == 'nbp'
      yum: name=firewalld state=present

    - name: start firewalld
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location == 'nbp'
      service: name=firewalld state=started enabled=yes

    - name: configure firewall trusted networks.
      notify:
        - restart firewalld
        - wait for SSH port coming up
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location == 'nbp' and project == 'pokemini'
      firewalld: permanent=true zone=trusted state=enabled source=10.101.102.0/24

    - name: configure firewall trusted networks.
      notify:
        - restart firewalld
        - wait for SSH port coming up
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location == 'nbp' and project != 'pokemini'
      firewalld: permanent=true zone=trusted state=enabled source="{{ item.address }}"
      with_items:
        - { address: "10.101.39.0/24" }
        - { address: "10.101.94.0/24" }

    - name: configure firewall access to well known services.
      notify:
        - restart firewalld
        - wait for SSH port coming up
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location == 'nbp'
      firewalld: permanent=true zone=public state=enabled rich_rule="rule family=ipv4 source address={{ item.address }} service name={{ item.service }} accept"
      with_items:
        - { address: "202.94.128.228", service: "ssh" }
        - { address: "152.165.119.106", service: "ssh" }
        - { address: "150.249.235.253", service: "ssh" }
        - { address: "13.114.208.147", service: "ssh" }
        - { address: "54.65.195.20", service: "ssh" }
        - { address: "52.199.176.73", service: "ssh" }
<<<<<<< HEAD
        - { address: "1.214.220.9", service: "ssh" }
        - { address: "1.214.220.10", service: "ssh" }
        - { address: "118.238.254.11", service: "ssh" }
        - { address: "10.11.0.0/16", service: "ssh" }
=======
        - { address: "1.214.220.10", service: "ssh" }
>>>>>>> 8adf4e9d94e2e1f3d2493783cd6db1ef624f8053
        - { address: "52.79.102.179", service: "ssh" }
        - { address: "52.79.103.88", service: "ssh" }

    - name: configure firewall reject ssh from anywhere.
      notify:
        - restart firewalld
        - wait for SSH port coming up
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and location == 'nbp'
      firewalld: permanent=true zone=public state=disabled service=ssh

  handlers:

    - name: restart firewalld
      service: name=firewalld state=restarted enabled=yes

    - name: wait for SSH port coming up
      wait_for: host={{ ansible_ssh_host }} port=22 delay=10 search_regex=OpenSSH
