---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: set hostname
      when: location != 'gcp' and location != 'ali'
      hostname: name={{ inventory_hostname }}

    - name: configure cloud init
      when: location is match('aws') and
            (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7) or
            (ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '14' or ansible_distribution_major_version == '18')) or 
            (ansible_distribution == "Amazon" and ansible_distribution_version == "2")
      copy: src={{ inventory_dir }}/files/common/cloud.cfg.{{ ansible_distribution }}{{ ansible_distribution_major_version }} dest=/etc/cloud/cloud.cfg
