---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - block:
      - name: install ius-release
        yum: name=https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm state=present

      - name: disable ius repo by default
        replace: dest={{ item }} regexp="^enabled *=.*" replace="enabled=0"
        with_items:
          - "/etc/yum.repos.d/ius.repo"
          - "/etc/yum.repos.d/ius-archive.repo"
          - "/etc/yum.repos.d/ius-testing.repo"
      when: location != 'ten' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7
