---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - block:
      - name: Delete firewalld
        yum: name=firewalld state=absent
      - name: Install firewalld-filesystem
        yum: name=http://mirror.centos.org/centos/7/os/x86_64/Packages/firewalld-filesystem-0.6.3-2.el7.noarch.rpm state=present
      when: location == 'ten' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7

    - name: install perl-Net-SNMP
      when: location != 'gcp' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 8
      dnf: name=perl-Net-SNMP enablerepo=epel,PowerTools state=present

    - name: install perl-Net-SNMP
      when: location == 'gcp' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 8
      dnf: name=perl-Net-SNMP enablerepo=epel,powertools state=present

    - name: install munin-node
      when: ansible_distribution == 'CentOS' or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")
      yum: name=munin-node enablerepo=epel state=present

    - name: install munin-node on Amazon Linux 1
      when: ansible_distribution == 'Amazon' and ansible_distribution_version == '2018.03'
      yum: name=munin-node state=present

    - name: install perl-Net-CIDR
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7
      yum: name=perl-Net-CIDR enablerepo=epel state=present

    - name: install munin-node
      when: ansible_distribution == 'Ubuntu'
      apt: name=munin-node state=present

    - name: configure munin-node
      notify: restart munin-node
      template: src={{ inventory_dir }}/templates/common/munin-node.conf.j2 dest=/etc/munin/munin-node.conf

    - name: modify memory plugin
      notify: restart munin-node
      copy: src={{ inventory_dir }}/files/common/munin/plugins/memory dest=/usr/share/munin/plugins/memory

    - set_fact:
        if_name: "{{ item }}"
      register: unused_interfaces
      #when: "ansible_{{ item|replace('-', '_') }}.ipv4.address is undefined"
      when: "ansible_{{ item|replace('-', '_') }}.ipv4 is undefined"
      with_items: "{{ ansible_interfaces }}"

    - set_fact:
        unused_if_names: "{{ unused_interfaces.results|selectattr('ansible_facts', 'defined')|map(attribute='ansible_facts.if_name')|list }}"

    - name: delete unused NIC munin plugins if_XXX
      notify: restart munin-node
      file: path=/etc/munin/plugins/if_{{ item }} state=absent
      with_items: "{{ unused_if_names }}"

    - name: delete unused NIC munin plugins if_err_XXX
      notify: restart munin-node
      file: path=/etc/munin/plugins/if_err_{{ item }} state=absent
      with_items: "{{ unused_if_names }}"

    - name: delete unused munin plugin nfsd
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7
      notify: restart munin-node
      file: path=/etc/munin/plugins/{{ item }} state=absent
      with_items:
        - "nfsd"
        - "nfsd4"
        - "ntp_kernel_err"
        - "ntp_kernel_pll_freq"
        - "ntp_kernel_pll_off"
        - "ntp_offset"
        - "ntp_states"
        - "postfix_mailqueue"
        - "postfix_mailvolume"

  handlers:

    - name: restart munin-node
      service: name=munin-node state=restarted enabled=yes
