---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: update ntpd
      when: location != 'ali' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6
      notify: restart ntpd
      yum: name="ntp*" state=latest

    - name: update chronyd
      when: location != 'ali' and location != 'ten' and ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2"))
      notify: restart chronyd
      yum: name="chrony,ntp*" state=latest

    - name: update ntpd
      when: ansible_distribution == 'Amazon' and ansible_distribution_version == '2018.03'
      notify: restart ntpd on Amazon Linux 1
      yum: name="ntp*" state=latest

    - name: update ntp
      when: location != 'ali' and ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
      notify: restart ntp
      apt: name="ntp" update_cache=yes state=latest

    - name: insert x option for ntpd
      when: location != 'ali' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6
      notify: restart ntpd
      replace: dest=/etc/sysconfig/ntpd regexp='^OPTIONS="(-u [^\"]+)"$' replace='OPTIONS="-x \1"'

    - name: insert x option for ntpd
      when: ansible_distribution == 'Amazon' and ansible_distribution_version == '2018.03'
      notify: restart ntpd on Amazon Linux 1
      replace: dest=/etc/sysconfig/ntpd regexp='^OPTIONS="(-g)"$' replace='OPTIONS="-x \1"'

    - name: insert x option for ntp
      when: location != 'ali' and ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
      notify: restart ntp
      replace: dest=/etc/default/ntp regexp="^NTPD_OPTS='(-g[^\']*)'$" replace="NTPD_OPTS='-x \1'"

    - block:
      - block:
        - name: Modify the ntp server
          lineinfile:
            dest: '/etc/ntp.conf'
            regexp: 'server 0.centos.pool.ntp.org iburst'
            line: 'server 10.101.39.23 iburst true'
            backrefs: yes
        - name: Delete the other ntp server
          lineinfile:
            dest: '/etc/ntp.conf'
            regexp: '^(.*)centos.pool.ntp.org iburst$'
            state: absent
        - name: Add the other ntp server
          lineinfile:
            dest: '/etc/ntp.conf'
            insertafter: 'server 10.101.39.23 iburst true'
            line: 'server 10.101.39.24 iburst'
            state: present
        - name: Restart NTP service
          service:
            name: ntpd
            state: restarted 
        when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6
      - block:
        - name: Modify the ntp server
          lineinfile:
            dest: '/etc/chrony.conf'
            regexp: 'server 0.centos.pool.ntp.org iburst'
            line: 'server 10.101.39.23 iburst'
            backrefs: yes
        - name: Delete the other ntp server
          lineinfile:
            dest: '/etc/chrony.conf'
            regexp: '^(.*)centos.pool.ntp.org iburst$'
            state: absent
        - name: Add the other ntp server
          lineinfile:
            dest: '/etc/chrony.conf'
            insertafter: 'server 10.101.39.23 iburst'
            line: 'server 10.101.39.24 iburst'
            state: present
        - name: Restart NTP service
          systemd:
            name: chronyd
            state: restarted 
        when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7
      when: location == 'nbp'

    - block:
      - block:
        - name: Modify the ntp server
          lineinfile:
            dest: '/etc/ntp.conf'
            regexp: 'server 0.centos.pool.ntp.org iburst'
            line: 'server 169.254.169.123 iburst'
            backrefs: yes
        - name: Delete the other ntp server
          lineinfile:
            dest: '/etc/ntp.conf'
            regexp: '^(.*)centos.pool.ntp.org iburst$'
            state: absent 
        - name: Restart NTP service
          service:
            name: ntpd
            state: restarted 
        when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6
      - block:
        - name: Modify the ntp server
          lineinfile:
            dest: '/etc/chrony.conf'
            regexp: 'server 0.centos.pool.ntp.org iburst'
            line: 'server 169.254.169.123 iburst'
            backrefs: yes
        - name: Delete the other ntp server
          lineinfile:
            dest: '/etc/chrony.conf'
            regexp: '^(.*)centos.pool.ntp.org iburst$'
            state: absent 
        - name: Restart NTP service
          systemd:
            name: chronyd
            state: restarted 
        when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7

      - block:
        - name: Modify the ntp server
          lineinfile:
            dest: '/etc/chrony.conf'
            regexp: 'pool 2.amazon.pool.ntp.org iburst'
            line: '#pool 2.amazon.pool.ntp.org iburst'
            backrefs: yes
        - name: Restart NTP service
          systemd:
            name: chronyd
            state: restarted
        when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
      when: location is match('aws')

  handlers:

    - name: restart ntpd
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6) or (location == 'ten' and ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7)
      service: name=ntpd state=restarted enabled=yes

    - name: restart ntpd on Amazon Linux 1
      when: ansible_distribution == 'Amazon' and ansible_distribution_version == '2018.03'
      service: name=ntpd state=restarted enabled=yes

    - name: restart chronyd
      when: location != 'ten' and ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2"))
      service: name=chronyd state=restarted enabled=yes

    - name: restart ntp
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
      service: name=ntp state=restarted enabled=yes
