---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: install Base packages
      when: ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"
      yum: name="@Base,@Development Tools" state=present

    - name: install Base packages
      when: ansible_distribution == 'Ubuntu'
      apt: name="unzip,git,build-essential" state=present
