---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: path settings.
      copy: src={{ inventory_dir }}/files/common/profile.d/path.sh dest=/etc/profile.d/path.sh

    - name: bash history settings.
      copy: src={{ inventory_dir }}/files/common/profile.d/history.sh dest=/etc/profile.d/history.sh

    - name: awscli settings
      copy: src={{ inventory_dir }}/files/common/profile.d/awscli.sh dest=/etc/profile.d/awscli.sh
