---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: install required package
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 7
      yum: name="libselinux-python" state=present

    - name: disable SELinux
      when: ansible_distribution == 'CentOS'
      selinux: state=disabled
