---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: monitoring sshd
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")
      lineinfile: >
        dest=/var/spool/cron/root
        line='*/10 * * * * systemctl status sshd.service >/dev/null 2>&1 || systemctl restart sshd.service >/dev/null 2>&1'
        create=yes

    - name: monitoring sshd
      when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int == 18)
      lineinfile: >
        dest=/var/spool/cron/crontabs/root
        line='*/10 * * * * systemctl status sshd.service >/dev/null 2>&1 || systemctl restart sshd.service >/dev/null 2>&1'
        create=yes
