---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: set sudo on Amazon Linux 1
      when: ansible_distribution == 'Amazon' and ansible_distribution_version == '2018.03'
      copy: src={{ inventory_dir }}/files/common/sudoers.d/infra dest=/etc/sudoers.d/infra mode=0440

    - name: set sudo
      when: ansible_distribution == 'Ubuntu'
      copy: src={{ inventory_dir }}/files/common/sudoers.d/admin dest=/etc/sudoers.d/admin mode=0440
