---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: Set the ntp server
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"
      template: 
        src: "{{ inventory_dir }}/templates/common/timesyncd.conf.{{ ansible_distribution }}{{ ansible_distribution_major_version }}.j2"
        dest: /etc/systemd/timesyncd.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart systemd-timesyncd


  handlers:

    - name: Restart systemd-timesyncd
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"
      systemd:
        name: systemd-timesyncd
        state: restarted
