---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: set timezone
      when: location == 'nbp'
      timezone: name=Asia/Seoul

    - name: set timezone
      when: location is match('aws') or location == 'gcp'
      timezone: name=Asia/Tokyo
