---


- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: stop tuned
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7
      service: name=tuned state=stopped enabled=no
