---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: create coco user (Pokecolo)
      when: ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")) and project == 'pokecolo'
      user: name=coco
            shell=/bin/bash
            groups=adm,wheel,systemd-journal
            append=yes

    - name: create coco user (Pokecolo)
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6 and project == 'pokecolo'
      user: name=coco
            shell=/bin/bash
            groups=wheel
            append=yes

    - name: create coco user (Pokemini)
      when: ((ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")) and project == 'pokemini'
      user: name=coco
            shell=/bin/bash
            groups=adm,wheel,systemd-journal
            append=yes

    - name: create coco user (Pokemini)
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6 and project == 'pokemini'
      user: name=coco
            shell=/bin/bash
            groups=wheel
            append=yes

    - name: set password coco user. (Pokecolo)
      when: project == 'pokecolo'
      user: name=coco
            password={{ lookup('file', "{{ inventory_dir }}/private/coco_password_hashed_pokecolo") }}

    - name: set password coco user. (Pokemini)
      when: project == 'pokemini'
      user: name=coco
            password={{ lookup('file', "{{ inventory_dir }}/private/coco_password_hashed_pokemini") }}
