---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: create dev_kr user
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6 and (project == 'mame' or project == 'kinder-mame')
      user: name=dev_kr
            shell=/bin/bash
            groups=wheel
            append=yes

    - name: create dev_kr user
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and (project == 'mame' or project == 'kinder-mame')
      user: name=dev_kr
            shell=/bin/bash
            groups=adm,wheel,systemd-journal
            append=yes

    - name: create dev_kr user
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int == 14 and (project == 'mame' or project == 'kinder-mame' or project == 'kadira')
      user: name=dev_kr
            shell=/bin/bash
            groups=adm,sudo
            append=yes

    - name: set dev_kr user password
      when: project == 'mame' or project == 'kinder-mame' or project == 'kadira'
      user: name=dev_kr
            password={{ lookup('file', '{{ inventory_dir }}/private/dev_kr_password_hashed') }}
