---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: create infra user for CentOS6
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6
      user: name=infra
            shell=/bin/bash
            groups=wheel
            append=yes

    - name: create infra user for Amazon Linux 1
      when: ansible_distribution == 'Amazon' and ansible_distribution_version == "2018.03"
      user: name=infra
            shell=/bin/bash
            groups=wheel
            append=yes

    - name: create infra user for CentOS7,8 or AmazonLinux2
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")
      user: name=infra
            shell=/bin/bash
            groups=adm,wheel,systemd-journal
            append=yes

    - name: create infra user for Ubuntu
      when: ansible_distribution == 'Ubuntu'
      user: name=infra
            shell=/bin/bash
            groups=adm,sudo
            append=yes

    - name: set infra user password
      user: name=infra
            password={{ lookup('file', '{{ inventory_dir }}/private/infra_password_hashed') }}

    - name: add infra user pubkey
      authorized_key: user=infra key="{{ item }}"
      with_file:
        - "{{ inventory_dir }}/private/public_keys/infra"
        - "{{ inventory_dir }}/private/public_keys/youn_seongwon"
        - "{{ inventory_dir }}/private/public_keys/nakano_daisuke"
        - "{{ inventory_dir }}/private/public_keys/myung_yangjae"
        - "{{ inventory_dir }}/private/public_keys/song_yunfeng"

    - name: add infra user pubkey
      when: project == 'pokemini' or project == 'tane' or project == 'projectx' or project == 'story' or project == 'colorhara'
      authorized_key: user=infra key="{{ item }}"
      with_file:
        - "{{ inventory_dir }}/private/public_keys/lee_jongil"
        - "{{ inventory_dir }}/private/public_keys/yoon_seokwoo"
        - "{{ inventory_dir }}/private/public_keys/kim_jonghee"
        - "{{ inventory_dir }}/private/public_keys/park_hyungkyu"

