---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  
  - name: Delete User centos
    user:
      name: "{{ item.name }}"
      state: absent
      remove: yes
      force: yes
    with_items:
      - { name: centos }
    when: location != 'gcp' and ansible_distribution == "CentOS"

  - name: Remove centos user from google-sudoers group
    command: /usr/bin/gpasswd -d centos google-sudoers
    when: location == 'gcp' and ansible_distribution == "CentOS"
    ignore_errors: yes
  
  - name: Delete User ec2-user
    user:
      name: "{{ item.name }}"
      state: absent
      remove: yes
      force: yes
    with_items:
      - { name: ec2-user }
    when: ansible_distribution == "Amazon"

