---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: create anysense user
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6 and project == 'pen-anysense'
      user: name=anysense
            shell=/bin/bash
            groups=wheel
            append=yes

    - name: create anysense user
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7 and project == 'pen-anysense'
      user: name=anysense
            shell=/bin/bash
            groups=adm,wheel,systemd-journal
            append=yes

    - name: set anysense user password
      when: project == 'pen-anysense'
      user: name=anysense
            password={{ lookup('file', '{{ inventory_dir }}/private/anysense_password_hashed') }}

    - name: add anysense user pubkey
      when: project == 'pen-anysense'
      authorized_key: user=anysense key="{{ item }}"
      with_file:
        - "{{ inventory_dir }}/private/public_keys/infra"
