---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: set root password nbp
      when: location == "nbp"
      user: name=root
            password={{ lookup('file', '{{ inventory_dir }}/private/root_password_hashed_nbp') }}

    - name: set root password aws
      when: location == "aws" or location == "gcp"
      user: name=root
            password={{ lookup('file', '{{ inventory_dir }}/private/root_password_hashed_aws') }}
