---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - block:
      - name: yum update on CentOS6,7 or AmazonLinux2
        yum:
          name:
            - kernel
            - nss
            - authconfig
            - bash
            - bind-utils
            - dstat
            - git
            - glibc*
            - net-snmp
            - nmap
            - nscd
            - nss-pam-ldapd
            - ntp
            - openldap-*
            - openssh-*
            - openssl-*
            - pam_ldap
            - postfix
            - sysstat
            - tcpdump
            - telnet
            - traceroute
            - vim
            - wget
            - yum-utils
            - libselinux-python
          state: latest
          update_cache: yes
        tags: yum_update
        when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 7) or (ansible_distribution == "Amazon" and ansible_distribution_version == "2")

      - name: yum update on CentOS 8
        yum:
          name:
            - kernel
            - nss
            - authconfig
            - bash
            - bind-utils
            - dstat
            - git
            - glibc*
            - openldap-*
            - openssh-*
            - openssl-*
            - pam_ldap
            - postfix
            - sysstat
            - tcpdump
            - telnet
            - vim
            - wget
          state: latest
          update_cache: yes
        tags: yum_update
        when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 8
      when: location != 'ali' and location != 'ten'
