---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: install zabbix-release on CentOS x86
      when: ansible_distribution == 'CentOS' and ansible_architecture == "x86_64"
      yum: name=http://repo.zabbix.com/zabbix/4.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-4.0-2.el{{ ansible_distribution_major_version }}.noarch.rpm state=present

    - name: install zabbix-release on Amazon Linux 1 x86
      when: ansible_distribution == 'Amazon' and ansible_distribution_version == '2018.03' and ansible_architecture == "x86_64"
      yum: name=http://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-2.el6.noarch.rpm state=present

    - name: install zabbix-release on Amazon Linux 2 x86
      when: ansible_distribution == 'Amazon' and ansible_distribution_version == "2" and ansible_architecture == "x86_64"
      yum: name=http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm state=present

    - name: disable zabbix repos x86 by default
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon') and ansible_architecture == "x86_64"
      replace: dest=/etc/yum.repos.d/zabbix.repo regexp="^enabled *=.*" replace="enabled=0"

    - name: install zabbix-agent x86
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon') and ansible_architecture == "x86_64"
      yum: name=zabbix-agent enablerepo=zabbix state=latest

    - name: install zabbix-agent on CentOS7,AmazonLinux2 Arm
      when: ((ansible_distribution == 'Amazon' and ansible_distribution_version == "2") or (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7)) and ansible_architecture == "aarch64"
      yum: name=https://cbs.centos.org/kojifiles/packages/zabbix/4.0.26/1.el7/aarch64/zabbix-agent-4.0.26-1.el7.aarch64.rpm state=present

    - name: install zabbix-agent
      when: ansible_distribution == 'Ubuntu'
      apt: name=zabbix-agent state=latest

    - name: configure zabbix-agent
      notify: restart zabbix-agent
      template: src={{ inventory_dir }}/templates/common/zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf

  handlers:

    - name: restart zabbix-agent
      service: name=zabbix-agent state=restarted enabled=yes
