---

- hosts: zabbix-agent
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - block:
      - name: Modify the Server
        lineinfile:
          dest: '/etc/zabbix/zabbix_agentd.conf'
          regexp: '^Server=(.*)$'
          line: 'Server=zabbix-aws.cocone.jp'
          backrefs: yes
      - name: Modify the ServerActive
        lineinfile:
          dest: '/etc/zabbix/zabbix_agentd.conf'
          regexp: '^ServerActive=(.*)$'
          line: 'ServerActive=zabbix-aws.cocone.jp'
          backrefs: yes
      when: location is match('aws')

    - block:
      - name: Modify the Server
        lineinfile:
          dest: '/etc/zabbix/zabbix_agentd.conf'
          regexp: '^Server=(.*)$'
          line: 'Server=zabbix-nbp.cocone.jp'
          backrefs: yes
      - name: Modify the ServerActive
        lineinfile:
          dest: '/etc/zabbix/zabbix_agentd.conf'
          regexp: '^ServerActive=(.*)$'
          line: 'ServerActive=zabbix-nbp.cocone.jp'
          backrefs: yes
      when: location == 'nbp'

    - block:
      - name: Modify the Server
        lineinfile:
          dest: '/etc/zabbix/zabbix_agentd.conf'
          regexp: '^Server=(.*)$'
          line: 'Server=zabbix-gcp.cocone.jp'
          backrefs: yes
      - name: Modify the ServerActive
        lineinfile:
          dest: '/etc/zabbix/zabbix_agentd.conf'
          regexp: '^ServerActive=(.*)$'
          line: 'ServerActive=zabbix-gcp.cocone.jp'
          backrefs: yes
      when: location == 'gcp'

    - block:
      - name: Modify the Server
        lineinfile:
          dest: '/etc/zabbix/zabbix_agentd.conf'
          regexp: '^Server=(.*)$'
          line: 'Server=zabbix-ten.ccnapps.cn'
          backrefs: yes
      - name: Modify the ServerActive
        lineinfile:
          dest: '/etc/zabbix/zabbix_agentd.conf'
          regexp: '^ServerActive=(.*)$'
          line: 'ServerActive=zabbix-ten.ccnapps.cn'
          backrefs: yes
      when: location == 'ten'

    - name: Restart zabbix-agent service
      service:
        name: zabbix-agent
        state: restarted 
